name: Pytest
on: [ push, pull_request ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync
      - name: Run tests
        run: uv run pytest tests